# Generated by Django 2.2 on 2019-04-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trace',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trace',
            name='latitude',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trace',
            name='longitude',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trace',
            name='start_time',
            field=models.CharField(max_length=50),
        ),
    ]
