# Generated by Django 2.2 on 2019-06-17 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_auto_20190405_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=500)),
                ('home_location', models.CharField(max_length=500)),
                ('home_coordinate', models.CharField(max_length=500)),
                ('work_location', models.CharField(max_length=500)),
                ('work_coordinate', models.CharField(max_length=500)),
                ('food_nums', models.IntegerField()),
                ('food_detail', models.CharField(max_length=500)),
                ('hotel_nums', models.IntegerField()),
                ('hotel_detail', models.CharField(max_length=500)),
                ('shopping_nums', models.IntegerField()),
                ('shopping_detail', models.CharField(max_length=500)),
                ('tourism_nums', models.IntegerField()),
                ('tourism_detail', models.CharField(max_length=500)),
                ('entertainment_nums', models.IntegerField()),
                ('entertainment_detail', models.CharField(max_length=500)),
                ('sport_nums', models.IntegerField()),
                ('sport_detail', models.CharField(max_length=500)),
                ('education_nums', models.IntegerField()),
                ('education_detail', models.CharField(max_length=500)),
                ('medical_nums', models.IntegerField()),
                ('medical_detail', models.CharField(max_length=500)),
                ('transportation_nums', models.IntegerField()),
                ('transportation_detail', models.CharField(max_length=500)),
                ('financial_nums', models.IntegerField()),
                ('financial_detail', models.CharField(max_length=500)),
                ('company_nums', models.IntegerField()),
                ('company_detail', models.CharField(max_length=500)),
                ('natural_nums', models.IntegerField()),
                ('natural_detail', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='trace',
            name='duration',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
