# Generated by Django 2.2 on 2019-06-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0003_auto_20190617_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trace',
            name='cluster',
            field=models.IntegerField(default=0),
        ),
    ]
